export const Questions = [
    {
        prompt: "What is my name?",
        optionA: "John",
        optionB: "Jake",
        optionC: "Josh",
        optionD: "Bijendra Mishra",
        asnwer: "optionD",
    },
    {
        prompt: "Which of this is not a programming language?",
        optionA: "Python",
        optionB: "JavaScript",
        optionC: "MC-03",
        optionD: "Java",
        asnwer: "optionC",
    },
    {
        prompt: "Which of this is not a javascript framework?",
        optionA: "React",
        optionB: "Angular",
        optionC: "Vue",
        optionD: "Java",
        asnwer: "optionD",
    },
    {
        prompt: "What does HTML stand for?",
        optionA: "HyperText Markup Language",
        optionB: "HyperText Markdown Language",
        optionC: "HyperText Markup Link",
        optionD: "HyperText Markdown Link",
        asnwer: "optionA",
    },
    {
        prompt: "What does CSS stand for?",
        optionA: "Cascading Style Sheets",
        optionB: "Cascading Style Scripts",
        optionC: "Cascading Style Syllabus",
        optionD: "Cascading Style Syntax",
        asnwer: "optionA",
    },
    {
        prompt: "What does SQL stand for?",
        optionA: "Structured Query Language",
        optionB: "Structured Query Link",
        optionC: "Structured Query List",
        optionD: "Structured Query Language",
        asnwer: "optionA",
    },
    {
        prompt: "What does JSON stand for?",
        optionA: "JavaScript Object Notation",
        optionB: "Java Object Notation",
        optionC: "JavaScript Object Network",
        optionD: "Java Object Network",
        asnwer: "optionA",
    },
    {
        prompt: "What does XML stand for?",
        optionA: "eXtensible Markup Language",
        optionB: "eXtensible Markdown Language",
        optionC: "eXtensible Markup Link",
        optionD: "eXtensible Markdown Link",
        asnwer: "optionA",
    },
    {
        prompt: "What does API stand for?",
        optionA: "Application Programming Interface",
        optionB: "Application Program Interface",
        optionC: "Application Programming Interlink",
        optionD: "Application Program Interlink",
        asnwer: "optionA",
    },
    {
        prompt: "What does HTTP stand for?",
        optionA: "Hypertext Transfer Protocol",
        optionB: "Hypertext Transfer Procedure",
        optionC: "Hypertext Transfer Program",
        optionD: "Hypertext Transfer Process",
        asnwer: "optionA",
    },
];